name: Update keys

on:
  schedule:
    # Run every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update keys
    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - branch: e1
            script_url: https://megacloud.tv/js/player/a/prod/e1-player.min.js

          - branch: e6
            script_url: https://rapid-cloud.co/js/player/prod/e6-player-v2.min.js

          - branch: e4
            script_url: https://rabbitstream.net/js/player/prod/e4-player.min.js

    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Dart
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Download the obfuscated script
        run: curl ${{ matrix.script_url }} --output .github/scripts/script.js

      - name: Run Dart script to extract key
        run: |
          cd .github/scripts  
          ls -la
          dart run extract_key.dart script.js

      - name: Checkout ${{ matrix.branch }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          path: key_repo

      - name: Update key if it differs
        run: |
          cd key_repo
          echo "Old -> $(cat key) || New -> $(cat ../key)"
          if [[ "$(cat key)" != "$(cat ../key)" ]]; then
            cp ../key .
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add key
            git commit --amend -m "chore: Updating key"
            git push --force
          fi
